version: "3"

services:
  study2024:
    container_name: study2024
    image: study2024
    ports:
      - 8000:8080
    volumes:
      - ./resources/measurement_units.json:/resources/measurement_units.json
      - ./resources/settings.json:/resources/settings.json
      - ./docs/recipe1.md:/docs/recipe1.md
      - ./docs/recipe2.md:/docs/recipe2.md
      - ./logs:/logs

  study2025:
    container_name: study2025
    image: study2024
    ports:
      - 8001:8080
    volumes:
      - ./resources/measurement_units.json:/resources/measurement_units.json
      - ./resources/settings.json:/resources/settings.json
      - ./docs/recipe1.md:/docs/recipe1.md
      - ./docs/recipe2.md:/docs/recipe2.md
      - ./logs:/logs

networks:
  default:
