from enum import Enum


class EventType(Enum):
    DELETE_NOMENCLATURE = 1
    CHANGE_NOMENCLATURE = 2
    CHANGE_RANGE = 3
    CHANGE_BLOCK_PERIOD = 4
    CHANGE_DATA_GENERATING_SETTING = 5
    LOG_INFO = 6
    LOG_DEBUG = 7
    LOG_ERROR = 8